nelmio_api_doc:
  documentation:
    info:
      title: Raketa Test Task API
      description: This is a sample API for Raketa backend test task
      version: 1.0.0
  areas:
    path_patterns:
      - ^/api(?!/doc$)